version: "3"

services:
  api:
    image: qitup_api:latest
    build:
      context: ../api

    restart: always

    ports:
      - "8081:8081"

    environment:
      PORT: "8081"
      SECURED: "false"
      HOST: "localhost"
      SIGNING_KEY:
      SPOTIFY_ID:
      SPOTIFY_SECRET:
      SESSION_SECRET:

    labels:
      - traefik.enable=true
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.qitup.ca
      - traefik.docker.network=proxy
      - traefik.port=8081
    networks:
      - internal
      - proxy

    depends_on:
      - mongodb
      - redis

networks:
  proxy:
    external: true
  internal:
    external: false
