// Code generated by "stringer -type=EventType player.go"; DO NOT EDIT.

package party

import "fmt"

const _EventType_name = "PlaybackStartPlaybackInterruptedItemChanged"

var _EventType_index = [...]uint8{0, 13, 32, 43}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
